-- 5.1. Works because BranchID is GENERATED BY DEFAULT AS IDENTITY so it automatically receives values
INSERT INTO Branches (ParentBranchID, BranchName, City, Address, Phone, IsActive)
VALUES (1, 'AutoPass Bucuresti Nord', 'Bucharest', 'Str. Dorobantilor 12', '021-500-500', TRUE);
-- 5.2. Doesn't work because there is no StudentID 999 in "students", so FK constraint is violated
INSERT INTO Enrollments (StudentID, CourseTypeID, BranchID, EnrollmentDate, Status)
VALUES (999, 1, 2, DATE '2024-11-01', 'Active');
-- 5.3. Doesn't work because email already exists.ERROR:  duplicate key value violates unique constraint "uq_students_email"
-- Key (email)=(andrei.popescu@email.ro) already exists. 
INSERT INTO Students (BranchID, FirstName, LastName, Email, Phone, CNP, DateOfBirth, RegistrationDate)
VALUES (2, 'Andrei', 'Popescu', 'andrei.popescu@email.ro','0721000009', '5010101123457', DATE '2005-01-01', DATE '2024-09-10');
-- 5.4. Doesn't work. ERROR:  new row for relation "lessons" violates check constraint "ck_lessons_duration"
--Failing row contains (46, 1, 1, 1, 2024-09-15 09:00:00, 10, Practical, Scheduled, null). 
INSERT INTO Lessons (EnrollmentID, InstructorID, VehicleID, LessonDate, DurationMinutes, LessonType, Status, Score)
VALUES (1, 1, 1, TIMESTAMP '2024-09-15 09:00:00', 10, 'Practical', 'Scheduled', NULL);
-- 5.5. Doesn't work. ERROR:  null value in column "lastname" of relation "students" violates not-null constraint
INSERT INTO Students (BranchID, FirstName, Email, Phone, CNP, DateOfBirth, RegistrationDate)
VALUES (2, 'Mihai', 'mihai.popescu@email.ro', '0721000010', '6020202123457', DATE '2006-02-02', DATE '2024-09-12');
