-- 4.1
CREATE TABLE Notes (
    NoteID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StudentID INT NOT NULL,
    NoteText VARCHAR(200) NOT NULL,
    CreatedAt DATE NOT NULL,
    CONSTRAINT FK_Notes_Student FOREIGN KEY (StudentID) REFERENCES Students (StudentID)
);
-- 4.2
ALTER TABLE Students ADD COLUMN ReferralSource VARCHAR(50) NULL;
-- 4.3
UPDATE Students SET ReferralSource = 'Unknown' WHERE ReferralSource IS NULL;
ALTER TABLE Students ALTER COLUMN ReferralSource SET NOT NULL;
ALTER TABLE Students ALTER COLUMN ReferralSource SET DEFAULT 'Unknown';
-- 4.4
CREATE OR REPLACE VIEW vw_ActiveStudents AS
SELECT StudentID, FirstName, LastName, Email FROM Students WHERE RegistrationDate > DATE '2024-01-01';
-- 4.5
ALTER TABLE Students DROP COLUMN ReferralSource;
