DROP DATABASE IF EXISTS autopass_workshop;
CREATE DATABASE autopass_workshop;
\connect autopass_workshop

-- -----------------------------------------------------------------------------
-- DDL
-- -----------------------------------------------------------------------------

CREATE TABLE Branches (
    BranchID        INT            GENERATED BY DEFAULT AS IDENTITY,
    ParentBranchID  INT            NULL,
    BranchName      VARCHAR(100)   NOT NULL,
    City            VARCHAR(100)   NOT NULL,
    Address         VARCHAR(200)   NOT NULL,
    Phone           VARCHAR(20)    NOT NULL,
    IsActive        BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_Branches PRIMARY KEY (BranchID),
    CONSTRAINT FK_Branches_Parent FOREIGN KEY (ParentBranchID) REFERENCES Branches (BranchID)
);

CREATE TABLE CourseTypes (
    CourseTypeID             INT           GENERATED BY DEFAULT AS IDENTITY,
    PrerequisiteCourseTypeID INT           NULL,
    CourseCode               VARCHAR(10)   NOT NULL,
    CourseName               VARCHAR(100)  NOT NULL,
    RequiredTheoryHours      INT           NOT NULL,
    RequiredPracticalHours   INT           NOT NULL,
    BasePrice                DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_CourseTypes PRIMARY KEY (CourseTypeID),
    CONSTRAINT UQ_CourseTypes_Code UNIQUE (CourseCode),
    CONSTRAINT FK_CourseTypes_Prerequisite FOREIGN KEY (PrerequisiteCourseTypeID) REFERENCES CourseTypes (CourseTypeID),
    CONSTRAINT CK_CourseTypes_Hours CHECK (RequiredTheoryHours >= 0 AND RequiredPracticalHours >= 0),
    CONSTRAINT CK_CourseTypes_Price CHECK (BasePrice > 0)
);

CREATE TABLE Instructors (
    InstructorID    INT           GENERATED BY DEFAULT AS IDENTITY,
    BranchID        INT           NOT NULL,
    FirstName       VARCHAR(50)   NOT NULL,
    LastName        VARCHAR(50)   NOT NULL,
    Email           VARCHAR(100)  NOT NULL,
    HireDate        DATE          NOT NULL,
    LicenseNumber   VARCHAR(30)   NOT NULL,
    HourlyRate      DECIMAL(8,2)  NOT NULL,
    IsActive        BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_Instructors PRIMARY KEY (InstructorID),
    CONSTRAINT UQ_Instructors_Email UNIQUE (Email),
    CONSTRAINT UQ_Instructors_License UNIQUE (LicenseNumber),
    CONSTRAINT FK_Instructors_Branch FOREIGN KEY (BranchID) REFERENCES Branches (BranchID),
    CONSTRAINT CK_Instructors_Rate CHECK (HourlyRate > 0)
);

CREATE TABLE Students (
    StudentID          INT          GENERATED BY DEFAULT AS IDENTITY,
    BranchID           INT          NOT NULL,
    FirstName          VARCHAR(50)  NOT NULL,
    LastName           VARCHAR(50)  NOT NULL,
    Email              VARCHAR(100) NOT NULL,
    Phone              VARCHAR(20)  NOT NULL,
    CNP                CHAR(13)     NOT NULL,
    DateOfBirth        DATE         NOT NULL,
    RegistrationDate   DATE         NOT NULL,
    CONSTRAINT PK_Students PRIMARY KEY (StudentID),
    CONSTRAINT UQ_Students_Email UNIQUE (Email),
    CONSTRAINT UQ_Students_CNP UNIQUE (CNP),
    CONSTRAINT FK_Students_Branch FOREIGN KEY (BranchID) REFERENCES Branches (BranchID)
);

CREATE TABLE Vehicles (
    VehicleID       INT          GENERATED BY DEFAULT AS IDENTITY,
    BranchID        INT          NOT NULL,
    LicensePlate    VARCHAR(15)  NOT NULL,
    Make            VARCHAR(50)  NOT NULL,
    Model           VARCHAR(50)  NOT NULL,
    Year            SMALLINT     NOT NULL,
    VehicleCategory VARCHAR(10)  NOT NULL,
    IsActive        BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_Vehicles PRIMARY KEY (VehicleID),
    CONSTRAINT UQ_Vehicles_Plate UNIQUE (LicensePlate),
    CONSTRAINT FK_Vehicles_Branch FOREIGN KEY (BranchID) REFERENCES Branches (BranchID),
    CONSTRAINT CK_Vehicles_Year CHECK (Year >= 1990 AND Year <= 2030)
);

CREATE TABLE Enrollments (
    EnrollmentID   INT         GENERATED BY DEFAULT AS IDENTITY,
    StudentID      INT         NOT NULL,
    CourseTypeID   INT         NOT NULL,
    BranchID       INT         NOT NULL,
    EnrollmentDate DATE        NOT NULL,
    Status         VARCHAR(20) NOT NULL,
    CONSTRAINT PK_Enrollments PRIMARY KEY (EnrollmentID),
    CONSTRAINT FK_Enrollments_Student FOREIGN KEY (StudentID) REFERENCES Students (StudentID),
    CONSTRAINT FK_Enrollments_CourseType FOREIGN KEY (CourseTypeID) REFERENCES CourseTypes (CourseTypeID),
    CONSTRAINT FK_Enrollments_Branch FOREIGN KEY (BranchID) REFERENCES Branches (BranchID),
    CONSTRAINT CK_Enrollments_Status CHECK (Status IN ('Active', 'Completed', 'Cancelled', 'Suspended'))
);

CREATE TABLE Lessons (
    LessonID        INT         GENERATED BY DEFAULT AS IDENTITY,
    EnrollmentID    INT         NOT NULL,
    InstructorID    INT         NOT NULL,
    VehicleID       INT         NULL,
    LessonDate      TIMESTAMP   NOT NULL,
    DurationMinutes INT         NOT NULL,
    LessonType      VARCHAR(20) NOT NULL,
    Status          VARCHAR(20) NOT NULL,
    Score           SMALLINT    NULL,
    CONSTRAINT PK_Lessons PRIMARY KEY (LessonID),
    CONSTRAINT FK_Lessons_Enrollment FOREIGN KEY (EnrollmentID) REFERENCES Enrollments (EnrollmentID),
    CONSTRAINT FK_Lessons_Instructor FOREIGN KEY (InstructorID) REFERENCES Instructors (InstructorID),
    CONSTRAINT FK_Lessons_Vehicle FOREIGN KEY (VehicleID) REFERENCES Vehicles (VehicleID),
    CONSTRAINT CK_Lessons_Type CHECK (LessonType IN ('Theory', 'Practical')),
    CONSTRAINT CK_Lessons_Status CHECK (Status IN ('Scheduled', 'Completed', 'Cancelled', 'NoShow')),
    CONSTRAINT CK_Lessons_Duration CHECK (DurationMinutes BETWEEN 30 AND 180),
    CONSTRAINT CK_Lessons_Score CHECK (Score IS NULL OR Score BETWEEN 1 AND 10)
);

CREATE TABLE Payments (
    PaymentID     INT           GENERATED BY DEFAULT AS IDENTITY,
    EnrollmentID  INT           NOT NULL,
    PaymentDate   TIMESTAMP     NOT NULL,
    Amount        DECIMAL(10,2) NOT NULL,
    PaymentMethod VARCHAR(30)   NOT NULL,
    PaymentStatus VARCHAR(20)   NOT NULL,
    CONSTRAINT PK_Payments PRIMARY KEY (PaymentID),
    CONSTRAINT FK_Payments_Enrollment FOREIGN KEY (EnrollmentID) REFERENCES Enrollments (EnrollmentID),
    CONSTRAINT CK_Payments_Amount CHECK (Amount > 0),
    CONSTRAINT CK_Payments_Method CHECK (PaymentMethod IN ('Cash', 'Card', 'BankTransfer')),
    CONSTRAINT CK_Payments_Status CHECK (PaymentStatus IN ('Completed', 'Pending', 'Refunded'))
);

-- -----------------------------------------------------------------------------
-- Synthetic data
-- -----------------------------------------------------------------------------

INSERT INTO Branches (BranchID, ParentBranchID, BranchName, City, Address, Phone, IsActive) OVERRIDING SYSTEM VALUE VALUES
(1, NULL, 'AutoPass Headquarters', 'Bucharest', 'Str. Kiseleff 10',        '021-100-100', TRUE),
(2, 1,    'AutoPass Pipera',       'Bucharest', 'Str. Aviatorilor 45',    '021-200-200', TRUE),
(3, 1,    'AutoPass Cluj',         'Cluj-Napoca', 'Str. Memorandumului 12', '0264-300-300', TRUE),
(4, 1,    'AutoPass Timisoara',    'Timisoara', 'Bd. Revolutiei 88',      '0256-400-400', TRUE);

INSERT INTO CourseTypes (CourseTypeID, PrerequisiteCourseTypeID, CourseCode, CourseName, RequiredTheoryHours, RequiredPracticalHours, BasePrice) OVERRIDING SYSTEM VALUE VALUES
(1, NULL, 'B',  'Category B — Passenger Car',    24, 30, 2500.00),
(2, 1,    'BE', 'Category BE — Car + Trailer',    8, 10, 1200.00),
(3, NULL, 'C',  'Category C — Truck',            32, 40, 4200.00),
(4, 3,    'CE', 'Category CE — Truck + Trailer', 10, 12, 1800.00),
(5, NULL, 'A2', 'Category A2 — Motorcycle',      16, 20, 1900.00);

INSERT INTO Instructors (InstructorID, BranchID, FirstName, LastName, Email, HireDate, LicenseNumber, HourlyRate, IsActive) OVERRIDING SYSTEM VALUE VALUES
(1,  2, 'Vasile',  'Popa',      'vasile.popa@autopass.ro',   '2019-03-01', 'INS-B-001',  85.00, TRUE),
(2,  2, 'Maria',   'Dobre',     'maria.dobre@autopass.ro',  '2020-06-15', 'INS-B-002',  80.00, TRUE),
(3,  2, 'Ion',     'Georgescu', 'ion.georgescu@autopass.ro','2021-01-10', 'INS-B-003',  78.00, TRUE),
(4,  3, 'Ana',     'Luca',      'ana.luca@autopass.ro',     '2018-09-01', 'INS-B-004',  90.00, TRUE),
(5,  3, 'Paul',    'Moldovan',  'paul.moldovan@autopass.ro','2022-04-20', 'INS-C-001',  95.00, TRUE),
(6,  3, 'Elena',   'Sava',      'elena.sava@autopass.ro',   '2020-11-05', 'INS-B-005',  82.00, TRUE),
(7,  4, 'Radu',    'Filip',     'radu.filip@autopass.ro',   '2019-07-12', 'INS-B-006',  84.00, TRUE),
(8,  4, 'Carmen',  'Neagu',     'carmen.neagu@autopass.ro', '2021-08-30', 'INS-A2-001', 75.00, TRUE),
(9,  2, 'Dragos',  'Preda',     'dragos.preda@autopass.ro', '2023-02-01', 'INS-B-007',  70.00, TRUE),
(10, 3, 'Irina',   'Barbu',     'irina.barbu@autopass.ro',  '2023-05-15', 'INS-B-008',  72.00, TRUE),
(11, 4, 'Bogdan',  'Stoica',    'bogdan.stoica@autopass.ro','2024-01-08', 'INS-C-002',  88.00, TRUE),
(12, 2, 'Oana',    'Creanga',   'oana.creanga@autopass.ro', '2024-06-01', 'INS-B-009',  68.00, TRUE);

INSERT INTO Students (StudentID, BranchID, FirstName, LastName, Email, Phone, CNP, DateOfBirth, RegistrationDate) OVERRIDING SYSTEM VALUE VALUES
(1,  2, 'Andrei',   'Popescu',  'andrei.popescu@email.ro',   '0721000001', '5010101123456', '2005-01-01', '2024-09-01'),
(2,  2, 'Ioana',    'Ionescu',  'ioana.ionescu@email.ro',    '0721000002', '6020202123456', '2006-02-02', '2024-09-05'),
(3,  2, 'Mihai',    'Dumitru',  'mihai.dumitru@email.ro',    '0721000003', '5030303123456', '2005-03-03', '2024-09-10'),
(4,  3, 'Elena',    'Stan',     'elena.stan@email.ro',       '0721000004', '6040404123456', '2006-04-04', '2024-09-12'),
(5,  3, 'Cristian', 'Marin',    'cristian.marin@email.ro',   '0721000005', '5050505123456', '2005-05-05', '2024-09-15'),
(6,  3, 'Diana',    'Radu',     'diana.radu@email.ro',       '0721000006', '6060606123456', '2006-06-06', '2024-10-01'),
(7,  4, 'Florin',   'Anghel',   'florin.anghel@email.ro',    '0721000007', '5070707123456', '2005-07-07', '2024-10-05'),
(8,  4, 'Laura',    'Dinu',     'laura.dinu@email.ro',       '0721000008', '6080808123456', '2006-08-08', '2024-10-08'),
(9,  2, 'Victor',   'Toma',     'victor.toma@email.ro',      '0721000009', '5090909123456', '2005-09-09', '2024-10-12'),
(10, 2, 'Raluca',   'Enache',   'raluca.enache@email.ro',    '0721000010', '6101010123456', '2006-10-10', '2024-10-15'),
(11, 3, 'Gabriel',  'Munteanu', 'gabriel.munteanu@email.ro', '0721000011', '5111111123456', '2005-11-11', '2024-11-01'),
(12, 3, 'Simona',   'Vlad',     'simona.vlad@email.ro',      '0721000012', '6121212123456', '2006-12-12', '2024-11-05'),
(13, 4, 'Teodor',   'Hanganu',  'teodor.hanganu@email.ro',   '0721000013', '5011313123456', '2005-01-13', '2024-11-08'),
(14, 4, 'Alina',    'Iordache', 'alina.iordache@email.ro',   '0721000014', '6021414123456', '2006-02-14', '2024-11-12'),
(15, 2, 'Nicolae',  'Gheorghe', 'nicolae.gheorghe@email.ro', '0721000015', '5031515123456', '2005-03-15', '2024-11-18'),
(16, 3, 'Monica',   'Preda',    'monica.preda@email.ro',     '0721000016', '6041616123456', '2006-04-16', '2024-12-01'),
(17, 4, 'George',   'Barbu',    'george.barbu@email.ro',     '0721000017', '5051717123456', '2005-05-17', '2024-12-05'),
(18, 2, 'Camelia',  'Ilie',     'camelia.ilie@email.ro',     '0721000018', '6061818123456', '2006-06-18', '2024-12-10');

INSERT INTO Vehicles (VehicleID, BranchID, LicensePlate, Make, Model, Year, VehicleCategory, IsActive) OVERRIDING SYSTEM VALUE VALUES
(1,  2, 'B-01-APX',  'Dacia',      'Logan',   2022, 'B',  TRUE),
(2,  2, 'B-02-APX',  'Volkswagen', 'Golf',   2021, 'B',  TRUE),
(3,  2, 'B-03-APX',  'Renault',    'Clio',    2023, 'B',  TRUE),
(4,  3, 'CJ-01-APX', 'Dacia',      'Logan',   2020, 'B',  TRUE),
(5,  3, 'CJ-02-APX', 'Mercedes',   'Actros',  2019, 'C',  TRUE),
(6,  3, 'CJ-03-APX', 'Ford',       'Focus',   2022, 'B',  TRUE),
(7,  4, 'TM-01-APX', 'Skoda',      'Octavia', 2021, 'B',  TRUE),
(8,  4, 'TM-02-APX', 'Yamaha',     'MT-07',   2022, 'A2', TRUE),
(9,  4, 'TM-03-APX', 'Dacia',      'Sandero', 2023, 'B',  TRUE),
(10, 2, 'B-04-APX',  'Hyundai',    'i20',     2024, 'B',  TRUE);

INSERT INTO Enrollments (EnrollmentID, StudentID, CourseTypeID, BranchID, EnrollmentDate, Status) OVERRIDING SYSTEM VALUE VALUES
(1,  1, 1, 2, '2024-09-01', 'Active'),
(2,  2, 1, 2, '2024-09-05', 'Active'),
(3,  3, 1, 2, '2024-09-10', 'Completed'),
(4,  4, 1, 3, '2024-09-12', 'Active'),
(5,  5, 3, 3, '2024-09-15', 'Active'),
(6,  6, 1, 3, '2024-10-01', 'Active'),
(7,  7, 1, 4, '2024-10-05', 'Completed'),
(8,  8, 5, 4, '2024-10-08', 'Active'),
(9,  9, 1, 2, '2024-10-12', 'Cancelled'),
(10, 10, 1, 2, '2024-10-15', 'Active'),
(11, 11, 3, 3, '2024-11-01', 'Active'),
(12, 12, 1, 3, '2024-11-05', 'Active'),
(13, 13, 1, 4, '2024-11-08', 'Active'),
(14, 14, 5, 4, '2024-11-12', 'Active'),
(15, 15, 1, 2, '2024-11-18', 'Active'),
(16, 16, 2, 3, '2024-12-01', 'Active'),
(17, 17, 1, 4, '2024-12-05', 'Active'),
(18, 18, 1, 2, '2024-12-10', 'Active'),
(19, 1,  2, 2, '2025-01-10', 'Active'),
(20, 3,  2, 2, '2025-01-15', 'Active'),
(21, 7,  2, 4, '2025-01-20', 'Active'),
(22, 4,  5, 3, '2025-02-01', 'Active'),
(23, 6,  1, 3, '2025-02-05', 'Suspended'),
(24, 11, 4, 3, '2025-02-10', 'Active'),
(25, 13, 5, 4, '2025-02-15', 'Active');

INSERT INTO Lessons (EnrollmentID, InstructorID, VehicleID, LessonDate, DurationMinutes, LessonType, Status, Score) VALUES
(1,  1, NULL, '2024-09-03 09:00:00', 90, 'Theory',    'Completed', 8),
(1,  1, 1,    '2024-09-10 10:00:00', 60, 'Practical', 'Completed', 7),
(1,  2, 2,    '2024-09-17 11:00:00', 60, 'Practical', 'Completed', 8),
(2,  2, NULL, '2024-09-06 14:00:00', 90, 'Theory',    'Completed', 9),
(2,  3, 3,    '2024-09-13 08:30:00', 60, 'Practical', 'Completed', 6),
(3,  1, NULL, '2024-09-08 09:00:00', 90, 'Theory',    'Completed', 10),
(3,  1, 1,    '2024-09-15 10:00:00', 60, 'Practical', 'Completed', 9),
(3,  2, 2,    '2024-09-22 11:00:00', 60, 'Practical', 'Completed', 9),
(4,  4, NULL, '2024-09-14 13:00:00', 90, 'Theory',    'Completed', 7),
(4,  6, 4,    '2024-09-21 09:00:00', 60, 'Practical', 'Completed', 8),
(5,  5, NULL, '2024-09-16 08:00:00', 90, 'Theory',    'Completed', 8),
(5,  5, 5,    '2024-09-23 07:30:00', 90, 'Practical', 'Completed', 7),
(6,  6, NULL, '2024-10-02 15:00:00', 90, 'Theory',    'Completed', 6),
(6,  10, 6,   '2024-10-09 10:00:00', 60, 'Practical', 'Completed', 7),
(7,  7, NULL, '2024-10-04 09:00:00', 90, 'Theory',    'Completed', 9),
(7,  7, 7,    '2024-10-11 11:00:00', 60, 'Practical', 'Completed', 10),
(7,  7, 7,    '2024-10-18 11:00:00', 60, 'Practical', 'Completed', 9),
(8,  8, NULL, '2024-10-07 16:00:00', 90, 'Theory',    'Completed', 8),
(8,  8, 8,    '2024-10-14 14:00:00', 60, 'Practical', 'Completed', 7),
(10, 3, NULL, '2024-10-14 09:00:00', 90, 'Theory',    'Completed', 8),
(10, 9, 10,   '2024-10-21 08:00:00', 60, 'Practical', 'Completed', 6),
(11, 5, NULL, '2024-11-02 08:00:00', 90, 'Theory',    'Completed', 7),
(11, 5, 5,    '2024-11-09 07:00:00', 90, 'Practical', 'Completed', 6),
(12, 4, NULL, '2024-11-06 13:00:00', 90, 'Theory',    'Completed', 9),
(12, 6, 4,    '2024-11-13 09:30:00', 60, 'Practical', 'Completed', 8),
(13, 7, NULL, '2024-11-09 10:00:00', 90, 'Theory',    'Completed', 7),
(13, 11, 9,   '2024-11-16 10:00:00', 60, 'Practical', 'Completed', 8),
(14, 8, NULL, '2024-11-13 15:00:00', 90, 'Theory',    'Completed', 8),
(14, 8, 8,    '2024-11-20 14:00:00', 60, 'Practical', 'Completed', 9),
(15, 12, NULL,'2024-11-19 09:00:00', 90, 'Theory',    'Completed', 7),
(15, 1, 1,    '2024-11-26 10:00:00', 60, 'Practical', 'Completed', 8),
(16, 4, NULL, '2024-12-02 12:00:00', 60, 'Theory',    'Completed', 8),
(16, 6, 4,    '2024-12-09 09:00:00', 60, 'Practical', 'Completed', 7),
(17, 7, NULL, '2024-12-06 11:00:00', 90, 'Theory',    'Completed', 6),
(17, 7, 7,    '2024-12-13 11:00:00', 60, 'Practical', 'Scheduled', NULL),
(18, 2, NULL, '2024-12-11 14:00:00', 90, 'Theory',    'Completed', 8),
(18, 3, 3,    '2024-12-18 08:30:00', 60, 'Practical', 'Completed', 7),
(19, 1, NULL, '2025-01-12 09:00:00', 60, 'Theory',    'Completed', 9),
(20, 2, 2,    '2025-01-18 10:00:00', 60, 'Practical', 'Completed', 8),
(21, 7, 7,    '2025-01-22 11:00:00', 60, 'Practical', 'Completed', 9),
(22, 8, 8,    '2025-02-03 14:00:00', 60, 'Practical', 'Completed', 7),
(23, 10, NULL,'2025-02-06 10:00:00', 90, 'Theory',    'Cancelled', NULL),
(24, 5, 5,    '2025-02-12 07:00:00', 90, 'Practical', 'Completed', 6),
(25, 8, 8,    '2025-02-16 15:00:00', 60, 'Practical', 'Completed', 8),
(9,  3, NULL, '2024-10-10 09:00:00', 90, 'Theory',    'Cancelled', NULL);

INSERT INTO Payments (EnrollmentID, PaymentDate, Amount, PaymentMethod, PaymentStatus) VALUES
(1,  '2024-09-01 10:00:00', 1250.00, 'Card',         'Completed'),
(1,  '2024-10-01 10:00:00', 1250.00, 'Card',         'Completed'),
(2,  '2024-09-05 11:00:00', 2500.00, 'BankTransfer', 'Completed'),
(3,  '2024-09-10 09:30:00', 2500.00, 'Cash',         'Completed'),
(4,  '2024-09-12 14:00:00', 1250.00, 'Card',         'Completed'),
(4,  '2024-10-12 14:00:00', 1250.00, 'Card',         'Pending'),
(5,  '2024-09-15 08:00:00', 2100.00, 'BankTransfer', 'Completed'),
(5,  '2024-11-15 08:00:00', 2100.00, 'BankTransfer', 'Completed'),
(6,  '2024-10-01 16:00:00', 2500.00, 'Card',         'Completed'),
(7,  '2024-10-05 10:00:00', 2500.00, 'Cash',         'Completed'),
(8,  '2024-10-08 12:00:00', 1900.00, 'Card',         'Completed'),
(10, '2024-10-15 09:00:00', 1250.00, 'Card',         'Completed'),
(10, '2024-11-15 09:00:00', 1250.00, 'Card',         'Completed'),
(11, '2024-11-01 08:30:00', 4200.00, 'BankTransfer', 'Completed'),
(12, '2024-11-05 13:00:00', 2500.00, 'Card',         'Completed'),
(13, '2024-11-08 11:00:00', 1250.00, 'Cash',         'Completed'),
(14, '2024-11-12 15:30:00', 1900.00, 'Card',         'Completed'),
(15, '2024-11-18 10:00:00', 2500.00, 'Card',         'Completed'),
(16, '2024-12-01 12:00:00', 1200.00, 'BankTransfer', 'Completed'),
(17, '2024-12-05 11:00:00', 1250.00, 'Card',         'Completed'),
(18, '2024-12-10 14:00:00', 1250.00, 'Card',         'Completed'),
(18, '2025-01-10 14:00:00', 1250.00, 'Card',         'Pending'),
(19, '2025-01-10 09:00:00', 1200.00, 'Card',         'Completed'),
(20, '2025-01-15 10:00:00', 1200.00, 'Cash',         'Completed'),
(21, '2025-01-20 11:00:00', 1200.00, 'Card',         'Completed'),
(22, '2025-02-01 13:00:00', 1900.00, 'Card',         'Completed'),
(23, '2025-02-05 10:00:00', 2500.00, 'BankTransfer', 'Refunded'),
(24, '2025-02-10 08:00:00', 1800.00, 'BankTransfer', 'Completed'),
(25, '2025-02-15 16:00:00', 1900.00, 'Card',         'Completed'),
(5,  '2025-01-15 08:00:00',  500.00, 'Cash',         'Completed'),
(11, '2025-02-01 08:30:00', 1000.00, 'BankTransfer', 'Pending'),
(7,  '2024-10-05 10:30:00',  800.00, 'Cash',         'Completed');

SELECT setval(pg_get_serial_sequence('branches', 'branchid'), (SELECT MAX(BranchID) FROM Branches));
SELECT setval(pg_get_serial_sequence('coursetypes', 'coursetypeid'), (SELECT MAX(CourseTypeID) FROM CourseTypes));
SELECT setval(pg_get_serial_sequence('instructors', 'instructorid'), (SELECT MAX(InstructorID) FROM Instructors));
SELECT setval(pg_get_serial_sequence('students', 'studentid'), (SELECT MAX(StudentID) FROM Students));
SELECT setval(pg_get_serial_sequence('vehicles', 'vehicleid'), (SELECT MAX(VehicleID) FROM Vehicles));
SELECT setval(pg_get_serial_sequence('enrollments', 'enrollmentid'), (SELECT MAX(EnrollmentID) FROM Enrollments));
SELECT setval(pg_get_serial_sequence('lessons', 'lessonid'), COALESCE((SELECT MAX(LessonID) FROM Lessons), 1));
SELECT setval(pg_get_serial_sequence('payments', 'paymentid'), COALESCE((SELECT MAX(PaymentID) FROM Payments), 1));
